import type { BattleAction, BattleState } from './turn'
import { RuleRuntime, withRuleRuntime, getActiveRuleRuntime, getActiveRuleExecutionContext, getRuleExecutionTriggerSystem } from './rule-runtime'
import { globalTriggerSystem } from './triggers'
import { finalizePendingOptionSession } from './pending-interaction'
import { getTargetingStateRevision, stampTargetingRevision, TargetingRuleError } from './targeting'
import { presentationRecordingRollback } from './battle-presentation-recording'
import { hashStable } from './battle-trace'

export interface SkillChoiceSource { type: 'skill' | 'card' | 'rule' | 'pending'; id: string; pieceId?: string }
export interface SkillChoiceInput {
  kind: 'target' | 'option'
  source: SkillChoiceSource
  /** Signature of a locally generated public prompt, not authority credentials. */
  promptKey: string
  targetPieceId?: string
  targetX?: number
  targetY?: number
  extraTargets?: Array<{ pieceId?: string; x?: number; y?: number }>
  selectedOption?: unknown
}

class SkillChoiceError extends Error {
  readonly code = 'TARGET_SKILL_CHOICES_INVALID'
}

function invalid(): never { throw new SkillChoiceError('Invalid skill choice sequence') }

/** Opaque equality guard for the public choice's meaning and candidate set. */
export function skillChoicePromptKey(kind: 'target' | 'option', pending: Record<string, unknown>): string {
  const fields: Record<string, unknown> = { kind }
  for (const key of ['source', 'title', 'step', 'selectionMode', 'min', 'max', 'minSelections', 'maxSelections', 'canCancel']) {
    if (pending[key] !== undefined) fields[key] = pending[key]
  }
  if (kind === 'target') {
    fields.targetType = pending.targetType === 'piece' ? 'piece' : 'cell'
    fields.candidates = pending.candidates ?? []
  } else fields.options = pending.options ?? []
  const transaction = pending.transaction as import('./suspendable-action-transaction').SuspendableActionTransaction | undefined
  const interaction = transaction?.currentInteraction
  if (interaction) {
    // In local preparation these are generated by the public replay itself.
    // Only their digest travels upstream; no authority transaction is sent.
    fields.event = interaction.eventType ?? ''
    fields.occurrence = interaction.consumerOrdinal
    fields.answerOccurrence = transaction!.answers.filter(answer => answer.key.consumerKind === interaction.consumerKind
      && answer.key.consumerId === interaction.consumerId && answer.key.sourceId === interaction.sourceId
      && answer.key.eventType === interaction.eventType && answer.key.consumerOrdinal === interaction.consumerOrdinal).length
  }
  return 'public-choice-v1-' + hashStable(fields)
}

/** Client-authored answers only; no transaction keys, code, seeds or credentials. */
export function readSkillChoices(value: unknown): SkillChoiceInput[] {
  if (!Array.isArray(value) || value.length > 16) invalid()
  const seen = new Set<object>()
  let nodes = 0
  const visit = (item: unknown, depth: number): void => {
    if (++nodes > 4096 || depth > 20) invalid()
    if (item === null || typeof item === 'boolean') return
    if (typeof item === 'string') { if (item.length > 4096) invalid(); return }
    if (typeof item === 'number') { if (!Number.isFinite(item)) invalid(); return }
    if (!item || typeof item !== 'object' || seen.has(item)
      || !Array.isArray(item) && Object.getPrototypeOf(item) !== Object.prototype) invalid()
    seen.add(item)
    if (Object.getOwnPropertySymbols(item).length || Array.isArray(item) && item.length > 64) invalid()
    for (const [key, descriptor] of Object.entries(Object.getOwnPropertyDescriptors(item))) {
      if (Array.isArray(item) && key === 'length') continue
      if (!('value' in descriptor) || ['__proto__', 'constructor', 'prototype'].includes(key)) invalid()
      visit(descriptor.value, depth + 1)
    }
    seen.delete(item)
  }
  visit(value, 0)
  const json = JSON.stringify(value)
  if (!json || json.length > 32768) invalid()
  const choices = JSON.parse(json) as SkillChoiceInput[]
  for (const choice of choices) {
    if (!choice || !['target', 'option'].includes(choice.kind) || !choice.source
      || !['skill', 'card', 'rule', 'pending'].includes(choice.source.type)
      || typeof choice.source.id !== 'string' || !choice.source.id.trim()
      || typeof choice.promptKey !== 'string' || !/^public-choice-v1-[a-f0-9]{64}$/.test(choice.promptKey)
      || choice.source.pieceId !== undefined && typeof choice.source.pieceId !== 'string') invalid()
    if (Object.keys(choice).some(key => !['kind', 'source', 'promptKey', 'targetPieceId', 'targetX', 'targetY', 'extraTargets', 'selectedOption'].includes(key))
      || Object.keys(choice.source).some(key => !['type', 'id', 'pieceId'].includes(key))) invalid()
    if (choice.kind === 'option') {
      if (!Object.hasOwn(choice, 'selectedOption') || ['targetPieceId', 'targetX', 'targetY', 'extraTargets'].some(key => Object.hasOwn(choice, key))) invalid()
    } else {
      if (Object.hasOwn(choice, 'selectedOption')) invalid()
      if (choice.targetPieceId !== undefined && (typeof choice.targetPieceId !== 'string' || !choice.targetPieceId)) invalid()
      const hasCell = Number.isSafeInteger(choice.targetX) && Number.isSafeInteger(choice.targetY)
      if (!choice.targetPieceId && !hasCell) invalid()
      if ((choice.targetX !== undefined || choice.targetY !== undefined) && !hasCell) invalid()
      if (choice.extraTargets !== undefined && (!Array.isArray(choice.extraTargets) || choice.extraTargets.length > 64)) invalid()
    }
  }
  return choices
}

export function skillChoiceMatchesPrompt(choice: SkillChoiceInput, state: BattleState, playerId: string): boolean {
  const pending = state.pendingTargetSelection ?? state.pendingOptionSelection
  if (!pending || pending.playerId?.trim().toLowerCase() !== playerId.trim().toLowerCase()) return false
  const kind = state.pendingTargetSelection ? 'target' : 'option'
  const source = pending.source
  return choice.kind === kind && !!source && source.type === choice.source.type
    && source.id === choice.source.id && source.pieceId === choice.source.pieceId
    && choice.promptKey === skillChoicePromptKey(kind, pending as unknown as Record<string, unknown>)
}

/** Reuse authority validation at every stage. Intermediate states never escape. */
export function applySkillChoiceSequence(
  state: BattleState,
  action: BattleAction & { skillChoices: SkillChoiceInput[] },
  reduce: (state: BattleState, action: BattleAction) => BattleState,
): BattleState {
  if (action.type !== 'useBasicSkill' && action.type !== 'useChargeSkill'
    || state.pendingTargetSelection || state.pendingOptionSelection) invalid()
  const choices = readSkillChoices(action.skillChoices)
  if (action.stateRevision !== undefined && action.stateRevision !== getTargetingStateRevision(state)) {
    throw new TargetingRuleError({ kind: 'invalid', code: 'TARGET_SELECTION_STALE', message: 'Skill choice root state revision is stale' })
  }
  const root = { ...action }
  delete (root as Partial<typeof root>).skillChoices
  const runtime = getActiveRuleRuntime()
  const runtimeSnapshot = runtime?.snapshot()
  const isolatedRuntime = runtime && runtimeSnapshot ? new RuleRuntime({
    rootSeed: runtime.rootSeed, tick: runtime.clock.tick, cursors: runtimeSnapshot.cursors,
  }) : undefined
  if (isolatedRuntime && runtimeSnapshot) isolatedRuntime.restore(runtimeSnapshot)
  const trigger = getRuleExecutionTriggerSystem(globalTriggerSystem)
  const triggerSnapshot = trigger.snapshotTransactionState()
  const context = getActiveRuleExecutionContext()
  const cache = context ? new Map(context.cache) : undefined
  const rollbackPresentation = presentationRecordingRollback()
  const execute = () => {
    let next = reduce(state, root)
    for (const choice of choices) {
      if (!next.pendingTargetSelection && !next.pendingOptionSelection) invalid()
      // A genuine hidden/random reaction may insert a different prompt. Do
      // not feed our answer to it or skip it; keep the authority pending flow.
      if (!skillChoiceMatchesPrompt(choice, next, action.playerId)) break
      const pending = next.pendingTargetSelection ?? next.pendingOptionSelection!
      const { kind, source: _source, promptKey: _promptKey, ...input } = choice
      void _source
      void _promptKey
      next = reduce(next, {
        ...input,
        type: kind === 'target' ? 'pendingTargetSelect' : 'pendingOptionSelect',
        playerId: action.playerId,
        selectionId: pending.selectionId,
        stateRevision: pending.stateRevision,
      } as BattleAction)
    }
    next = stampTargetingRevision(state, next)
    if (next.pendingOptionSelection) next.pendingOptionSelection = finalizePendingOptionSession(next.pendingOptionSelection, next.targetingRevision!)
    return next
  }
  try {
    const next = isolatedRuntime ? withRuleRuntime(isolatedRuntime, execute) : execute()
    if (runtime && isolatedRuntime) runtime.restore(isolatedRuntime.snapshot())
    return next
  } catch (error) {
    trigger.restoreTransactionState(triggerSnapshot)
    if (context && cache) { context.cache.clear(); for (const [key, value] of cache) context.cache.set(key, value) }
    rollbackPresentation()
    throw error
  }
}
